#!/bin/bash

echo "All variables passed to the script $@"
echo "All variables passed to the script $*"
echo "script name: $0"
echo "current directory: $pwd"
echo "who is running this: $user"
echo "home directory of user: $home"
echo "PID of this script: $$"

