#!/bin/bash

echo "please enter the number"
read NUMBER

if [ $(($NUMBER % 2)) -eq 0 ]; then
    echo "Given NUMBER is EVEN"
else
    echo "Given NUMBER is ODD"
fi

echo "Enter number"
read NUMBER

if [ $(($NUMBER -le 1)) ]; then
    echo "Given NUMBER is PRIME NUMBER"
fi