#!/bin/bash

"PERSON1=Ram"
"PERSON2=Raheem"
echo"PERSON1::Hi PERSON2, How are you? "
echo"PERSON2::Hi PERSON1, im fine.How are you?"
echo"PERSON1::What are you learning"
echo"PERSON2::Iam learning shell scripting PERSON1"